openapi: 3.0.0
info:
  title: Person API
  description: API for managing persons.
  version: 1.0.0
servers:
  - url: "http://localhost:8080"
    description: "Local"

paths:
  /person:
    post:
      tags:
        - "Person"
      summary: Save a new Person
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonInput'
      responses:
        '201':
          description: Person created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '400':
          description: Bad Request

    get:
      tags:
        - "Person"
      summary: Retrieve all persons
      responses:
        '200':
          description: A list of persons
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
        '500':
          description: Internal Server Error

components:
  schemas:
    Person:
      type: object
      properties:
        id:
          type: Integer
          example: 1
        middleName:
          type: string
          example: Doe
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Mike
        age:
          type: integer
          example: 10


    PersonInput:
      type: object
      properties:
        middleName:
          type: string
          example: Doe
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Mike
        age:
          type: integer
          example: 10
      required:
        - firstName
        - middleName
        - lastName
        - age
