spring:
  application:
    name: read-replica-poc
  primary:
    datasource:
      url: jdbc:mysql://localhost:3306/personmanagement?createDatabaseIfNotExist=true
      driver: com.mysql.jdbc.Driver
      username: primarydbuser
      password: password
  read-only:
    datasource:
      url: jdbc:mysql://localhost:3307/personmanagement?createDatabaseIfNotExist=true
      driver: com.mysql.jdbc.Driver
      username: readdbuser
      password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
