version: '3.8'

services:
  mysql-primary:
    image: mysql:8.0
    container_name: mysql-primary
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: personmanagement
      MYSQL_USER: syncuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    command: --server-id=1 --log-bin=mysql-bin --binlog_format=ROW

  mysql-replica:
    image: mysql:8.0
    container_name: mysql-replica
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: personmanagement
      MYSQL_USER: syncuser
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    depends_on:
      - mysql-primary
    command: --server-id=2 --log-bin=mysql-bin --binlog_format=ROW